Repository team-popo-world/parent-popo-world-front, pull requests merged in 2025-06, with the labels that each got.

#9 [UI] : 저축통장 페이지 퍼블리싱 #7
  package-lock.json
  package.json
  src/App.tsx
  src/api/savings/dummyData.ts
  src/api/savings/type.ts
  src/features/savings/DonutChart.tsx
  src/features/savings/NavigationButton.tsx
  src/features/savings/SavingsCard.tsx
  src/features/savings/SavingsHistoryModal.tsx
  src/features/savings/SavingsHistoryRow.tsx
  src/page/savings/layout.tsx
  src/page/savings/report/index.tsx
Labels: 🎨 ui, 현기

#15 [FEAT] : savings api 연동
  package-lock.json
  package.json
  src/api/savings/api.ts
  src/api/savings/dummyData.ts
  src/api/savings/type.ts
  src/features/home/HomeSavingsCard.tsx
  src/features/savings/SavingsCard.tsx
  src/features/savings/SavingsHistoryModal.tsx
  src/features/savings/SavingsHistoryRow.tsx
  src/page/home/home.tsx
  src/page/savings/report/index.tsx
Labels: bug, 현기, ✨feat

#18 [FEAT] : 저축통장 완료여부 추가
  dev-dist/sw.js
  src/features/savings/SavingsCard.tsx
  src/page/savings/report/index.tsx
Labels: 현기, ✨feat

#20 [UI] : navibar, mypage
  dev-dist/sw.js
  src/App.tsx
  src/assets/image/navbar/analyzeIcon.png
  src/assets/image/navbar/homeIcon.png
  src/assets/image/navbar/mypageIcon.png
  src/assets/image/navbar/shopIcon.png
  src/components/nav-bar/BottomNavBar.tsx
  src/components/nav-bar/index.ts
  src/page/auth/sign-in/index.tsx
  src/page/home/home.tsx
  src/page/layout.tsx
  src/page/mypage/index.tsx
  src/zustand/auth.ts
Labels: 🎨 ui, 현기

#22 [FEAT] 퀘스트 분석 연동 추가
  dev-dist/sw.js
  src/App.tsx
  src/api/api.ts
  src/features/home/HomeQuestCard.tsx
  src/page/AnalyzeCenter/quest/QuestApprovalTime.tsx
  src/page/AnalyzeCenter/quest/QuestCompletionChart.tsx
  src/page/AnalyzeCenter/quest/QuestCompletionTimeChart.tsx
  src/page/AnalyzeCenter/quest/QuestRewardScatterChart.tsx
  src/page/AnalyzeCenter/quest/index.tsx
  src/page/home/home.tsx
Labels: 은비, ✨feat

#26 [REFACTOR]: 페이지별 네비바, 포커스 수정
  dev-dist/sw.js
  src/App.tsx
  src/api/savings/type.ts
  src/components/modal/Modal.tsx
  src/components/nav-bar/BottomNavBar.tsx
  src/components/nav-bar/ChildNavBar.tsx
  src/features/home/ChildCard.tsx
  src/features/savings/SavingsHistoryModal.tsx
  src/page/AnalyzeCenter/index.tsx
  src/page/AnalyzeCenter/layout.tsx
  src/page/AnalyzeCenter/store/ProductAnalyzePage.tsx
  src/page/home/home.tsx
  src/page/invest/scenario-select/ChatBot.tsx
  src/page/invest/scenario-select/index.tsx
  src/page/mypage/index.tsx
  src/page/savings/report/index.tsx
  src/page/store/product-management/index.tsx
  src/utils/scrolltoTop.ts
  src/zustand/modal.ts
Labels: 현기, ♻️ refactor

#27 [REFACTOR] : my page 수정
  src/assets/image/common/home_background.png
  src/assets/image/common/home_page_background.png
  src/features/home/HomeQuestCard.tsx
  src/page/home/home.tsx
  src/page/mypage/index.tsx
  src/page/store/product-management/index.tsx
Labels: 현기, ♻️ refactor
